apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    apps: nginx-deployment
    type: front-end
spec:
  template:
    metadata:
      name: nginx-deployment
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.1
          ports:
            - containerPort: 80
  replicas: 30
  selector:
    matchLabels:
      type: front-end