apiVersion: v1
kind: ReplicationController
metadata:
  name: front-end
  labels:
    app: nginx
    type: front-end

spec:
  template:
    metadata:
      name: front-end
      labels:
        app: mynginx-app1
        type: front-end
    spec:
      containers:
        - name: myfirst-app-container
          image: nginx
  replicas: 2
